plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'maven-publish'
}

version = project.mod_version
group = project.maven_group
def modVersion = project.version.toString()

base { archivesName = project.archives_base_name }

repositories {
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/releases/"
    }
}

loom {
    splitEnvironmentSourceSets()
    mods {
        "storagefinder" { sourceSet sourceSets.client }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-lifecycle-events-v1:${project.fabric_lifecycle_events_version}"
    implementation "net.fabricmc.fabric-api:fabric-rendering-v1:${project.fabric_rendering_version}"
    implementation "net.fabricmc.fabric-api:fabric-key-mapping-api-v1:${project.fabric_key_mapping_api_version}"
    compileOnly("com.terraformersmc:modmenu:${project.modmenu_version}") {
        transitive = false
    }
}

tasks.withType(ProcessResources).configureEach {
    inputs.property "version", modVersion
    filesMatching("fabric.mod.json") { expand "version": modVersion }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
    it.options.encoding = "UTF-8"
    it.options.compilerArgs += ["-Xlint:deprecation"]
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(25)
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}
